### ISSUE TITLE
大佬 我也想搭建一个你这样的抖音下载网站 怎么搭建啊？？？

### ISSUE THREAD

**Issue by Hello-everybody** [missuo/DouyinParsing#4]
大佬 我也想搭建一个你这样的抖音下载网站 怎么搭建啊，小白 真心请教学习的，谢谢开发的这么好的工具

**Comment by missuo** [comment]
网页版代码暂不开源。如果您兴趣可以学习一下HTML、CSS、JS，使用我的接口，AJAX发送POST/GET请求即可。

**Comment by Hello-everybody** [comment]
好哒&nbsp; 谢谢&nbsp; 但是那调用接口我暂时不知道怎么操作&nbsp; &nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月27日(星期六) 晚上10:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [missuo/DouyinParsing] 大佬 我也想搭建一个你这样的抖音下载网站 怎么搭建啊？？？ (#4)





 
网页版代码暂不开源。如果您兴趣可以学习一下HTML、CSS、JS，使用我的接口，AJAX发送POST/GET请求即可。

**Comment by missuo** [comment]
我可以一直维护我的项目，你可以用我的网站。

**Comment by Hello-everybody** [comment]
好哒&nbsp; &nbsp; 我可以赞助你&nbsp; &nbsp;嘻嘻




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月27日(星期六) 晚上11:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [missuo/DouyinParsing] 大佬 我也想搭建一个你这样的抖音下载网站 怎么搭建啊？？？ (#4)





 
我可以一直维护我的项目，你可以用我的网站。

**Comment by missuo** [comment]
谢谢
