### ISSUE TITLE
大佬能出个下载海外版抖音无水印视频的吗？

### ISSUE THREAD

**Issue by MartinChristopher** [missuo/DouyinParsing#5]
大佬能出个下载海外版抖音无水印视频的吗？

**Comment by missuo** [comment]
TikTok我暂时不知道怎么去水印。。

**Comment by 96bit** [comment]
https://zztik.com. 这个网站你可以了解一下
> 大佬能出个下载海外版抖音无水印视频的吗？

**Comment by missuo** [comment]
网站没用啊，我不知道API是什么。。。
