### ISSUE TITLE
$ is not defined

### ISSUE THREAD

**Issue by daimazhan** [missuo/DouyinParsing#7]
It might has some issues on the web version, the console says: $ is not defined.

**Comment by missuo** [comment]
Please give me a screenshot and the parameters you passed in

**Comment by daimazhan** [comment]
It's a normal link from douyin, which my clients send to me several months ago.

> 5.35 xfo:/ 只要思想不滑坡，办法总比困难多😂%搞笑视频 %万万没想到 %看一遍笑一遍   https://v.douyin.com/NSBmxhE/ 复制此链接，打开Dou音搜索，直接观看视频！

I just checked the link, the video was deleted, sorry...

I used another link and it works.

I guess it would be really nice to remind user that the links they are trying to parsing is valid or not.

**Comment by missuo** [comment]
> "I guess it would be really nice to remind user that the links they are trying to parsing is valid or not."

**Maybe in a future version I'll add this feature, thanks for your feedback.**
