### ISSUE TITLE
Incomputive URL is incorrect

### ISSUE THREAD

**Issue by keizaken** [missuo/DouyinParsing#8]
I use the https://api.missuo.me/douyin API, previously there was no problem, but since 2 days yesterday it always shows an error : 
 
{
 "code": 404,
    "status": "failed",
    "msg": "Incomputive URL is incorrect!"
}

**Comment by missuo** [comment]
Known Issue. Sorry, I no longer plan to offer the free parsing API, but you can still use [dy.nisekoo.com](https://dy.nisekoo.com).

**Comment by keizaken** [comment]
I understand, thank you
